---
services:
  db:
    image: prasanthiandela/flm2026:dbimg
    ports:
      - "3306:3306"
    deploy:
      replicas: 1

  auth_service:
    image: prasanthiandela/flm2026:authimg
    ports:
      - "5001:5001"
    deploy:
      replicas: 1
    depends_on:
      - db
  book_service:
    image: prasanthiandela/flm2026:bookimg
    ports:
      - "5002:5002"
    deploy:
      replicas: 1
    depends_on:
      - db
  borrow_service:
    image: prasanthiandela/flm2026:borrowimg
    ports:
      - "5003:5003"
    deploy:
      replicas: 1
    depends_on:
      - db
  app_service:
    image: prasanthiandela/flm2026:appimg
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
    depends_on:
      - auth_service
      - book_service
      - borrow_service
